#define LANG_STRINGS_NUM 70

#define FOREACH_STR(FUNC) \
	FUNC(STR_YES) \
	FUNC(STR_NO) \
	FUNC(STR_GLES1_DESC) \
	FUNC(STR_BILINEAR_DESC) \
	FUNC(STR_PLAT_TARGET_DESC) \
	FUNC(STR_DEBUG_SHADERS_DESC) \
	FUNC(STR_DEBUG_MODE_DESC) \
	FUNC(STR_SPLASH_SKIP_DESC) \
	FUNC(STR_EXTRA_MEM_DESC) \
	FUNC(STR_OPTIMIZE_DESC) \
	FUNC(STR_EXTRA_POOL_DESC) \
	FUNC(STR_COMPRESS_DESC) \
	FUNC(STR_VIDEO_PLAYER_DESC) \
	FUNC(STR_NETWORK_DESC) \
	FUNC(STR_SQUEEZE_DESC) \
	FUNC(STR_SEARCH_UPDATES) \
	FUNC(STR_CHANGELIST) \
	FUNC(STR_UPDATE) \
	FUNC(STR_COMPAT_LIST) \
	FUNC(STR_SETTINGS) \
	FUNC(STR_BANNERS) \
	FUNC(STR_GLES1) \
	FUNC(STR_PLAT_TARGET) \
	FUNC(STR_EXTRA_MEM) \
	FUNC(STR_EXTRA_POOL) \
	FUNC(STR_SQUEEZE) \
	FUNC(STR_VIDEO_PLAYER) \
	FUNC(STR_NETWORK) \
	FUNC(STR_BILINEAR) \
	FUNC(STR_COMPRESS) \
	FUNC(STR_SPLASH_SKIP) \
	FUNC(STR_DEBUG_MODE) \
	FUNC(STR_DEBUG_SHADERS) \
	FUNC(STR_OPTIMIZE) \
	FUNC(STR_OPTIMIZE_END) \
	FUNC(STR_REDUCED) \
	FUNC(STR_OPTIMIZATION) \
	FUNC(STR_GAME_ID) \
	FUNC(STR_SIZE) \
	FUNC(STR_PLAYABLE) \
	FUNC(STR_INGAME_PLUS) \
	FUNC(STR_INGAME_MINUS) \
	FUNC(STR_CRASH) \
	FUNC(STR_SORT) \
	FUNC(STR_SETTINGS_INSTR) \
	FUNC(STR_SORT_INSTR) \
	FUNC(STR_BANNERS_INSTR) \
	FUNC(STR_NAME_ASC) \
	FUNC(STR_NAME_DESC) \
	FUNC(STR_SHACCCG_ERROR) \
	FUNC(STR_EXTRACTING) \
	FUNC(STR_GAME_ID_EXTR) \
	FUNC(STR_NEWS) \
	FUNC(STR_CONTINUE) \
	FUNC(STR_ANIM_BANNER) \
	FUNC(STR_ANIM_BANNER_INSTR) \
	FUNC(STR_FILTER_BY) \
	FUNC(STR_NO_FILTER) \
	FUNC(STR_NO_TAGS) \
	FUNC(STR_KEYMAP) \
	FUNC(STR_EXTERNALIZE_DROID) \
	FUNC(STR_EXTERNALIZE_AUDIOGROUP) \
	FUNC(STR_EXTERNALIZE) \
	FUNC(STR_EXTERNALIZE_DESC) \
	FUNC(STR_AUDIO) \
	FUNC(STR_AUDIO_DESC) \
	FUNC(STR_DOUBLE_BUFFERING) \
	FUNC(STR_DOUBLE_BUFFERING_DESC) \
	FUNC(STR_UNCACHED_MEM) \
	FUNC(STR_UNCACHED_MEM_DESC)

#define GET_VALUE(x) x,
#define GET_STRING(x) #x,

enum {
	FOREACH_STR(GET_VALUE)
};

#define LANG_ID_SIZE   64
#define LANG_STR_SIZE 1024
extern char lang_identifiers[LANG_STRINGS_NUM][LANG_ID_SIZE];
extern char lang_strings[LANG_STRINGS_NUM][LANG_STR_SIZE];
